### ISSUE TITLE
Account linking object definition

### ISSUE THREAD

**Issue by ak-cloud** [actions-on-google/actions-builder-account-linking-nodejs#1]
Please can you add links to Schemas these documentations are referring to? There is life beyond firebase and google services and I have spent 2 hrs searching how I can use OAUTH Authcode flow. 

This page talks about how I can define it on console https://developers.google.com/assistant/identity/oauth2?oauth=code

For my life I can't find the toggle button they are talking about.

**Comment by Fleker** [comment]
This is referring to the [Actions Console](https://console.actions.google.com/).

**Comment by ak-cloud** [comment]
> This is referring to the [Actions Console](https://console.actions.google.com/).

That link takes me to action console. But I have found the schema definition at https://developers.google.com/assistant/actionssdk/reference/rest/Shared.Types/AccountLinking?hl=en
I get 500 error for AUTH_CODE grant when I try and sink cli project. But I guess that's not an issue with this Github project and you can close the issue.
